# Generated by Django 4.0.5 on 2022-06-30 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothingdata',
            name='like',
        ),
        migrations.AddField(
            model_name='clothingdata',
            name='image',
            field=models.ImageField(null=True, upload_to='clothing_image'),
        ),
    ]
