# Generated by Django 4.0.4 on 2022-06-02 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notepad',
            name='title',
        ),
    ]
