# Generated by Django 4.0.4 on 2022-07-06 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='musinsaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('brand', models.URLField()),
                ('name', models.URLField()),
                ('rank', models.CharField(max_length=10)),
                ('price', models.CharField(max_length=10)),
                ('likes', models.CharField(max_length=10)),
            ],
        ),
    ]
