# Generated by Django 3.0.8 on 2022-06-29 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothesapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='heart',
        ),
        migrations.AlterField(
            model_name='product',
            name='rank',
            field=models.CharField(max_length=10),
        ),
    ]
