# Generated by Django 3.2.5 on 2022-05-26 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='data',
            new_name='reg_date',
        ),
    ]
