# Generated by Django 4.0.5 on 2022-06-29 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClothingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(max_length=30)),
                ('brand', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=50)),
                ('product', models.CharField(max_length=200)),
                ('like', models.CharField(max_length=50)),
            ],
        ),
    ]
