# Generated by Django 4.0.5 on 2022-07-04 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0002_remove_clothingdata_like_clothingdata_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothingdata',
            name='brand',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='clothingdata',
            name='product',
            field=models.CharField(max_length=100),
        ),
    ]
