# Generated by Django 4.0.5 on 2022-07-07 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0003_alter_clothingdata_brand_alter_clothingdata_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=300)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
