# Generated by Django 4.0.5 on 2022-07-07 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0004_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='userid',
            new_name='username',
        ),
    ]
