# Generated by Django 4.0.5 on 2022-07-20 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0006_alter_user_name_alter_user_password_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
