# Generated by Django 4.0.4 on 2022-06-29 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.TextField()),
                ('img', models.TextField()),
                ('brand', models.TextField()),
                ('item', models.TextField()),
                ('price', models.TextField()),
            ],
        ),
    ]
