# Generated by Django 3.2.5 on 2022-06-29 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('brand_name', models.TextField()),
                ('goods_name', models.TextField()),
                ('price', models.IntegerField()),
                ('recommand_cnt', models.IntegerField()),
            ],
        ),
    ]
