# Generated by Django 3.1.3 on 2022-07-06 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=300)),
                ('password', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
