# Generated by Django 3.2.5 on 2022-06-29 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='price',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='goods',
            name='rank',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='goods',
            name='recommand_cnt',
            field=models.TextField(),
        ),
    ]
