# Generated by Django 3.2.13 on 2022-06-29 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InfoId', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('Name', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('Image', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('Brand', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('Price', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('Rank', models.CharField(blank=True, default='', max_length=50, null=True)),
            ],
        ),
    ]
