# Generated by Django 4.0.6 on 2022-07-06 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchmodel',
            name='Image',
            field=models.URLField(blank=True, default='', max_length=50, null=True),
        ),
    ]
