# Generated by Django 4.0.6 on 2022-07-06 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0002_alter_searchmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchmodel',
            name='Image',
            field=models.URLField(),
        ),
    ]
