# Generated by Django 4.0.4 on 2022-07-03 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('brand', models.CharField(max_length=20)),
                ('items', models.CharField(max_length=30)),
                ('rank', models.CharField(max_length=10)),
                ('price', models.CharField(max_length=10)),
                ('likes', models.CharField(max_length=10)),
            ],
        ),
    ]
