# Generated by Django 4.0.4 on 2022-07-03 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='brand',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='items',
            field=models.URLField(),
        ),
    ]
