# Generated by Django 3.2.5 on 2022-05-29 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memo',
            old_name='create_date',
            new_name='date',
        ),
    ]
